name: "${project.name}"
version: "${project.version}"
author: MEFRREEX
api: ["1.0.13"]
main: com.mefrreex.mines.Mines

depend:
  - FormConstructor

permission:
  mines.admin:
    default: op